books/urls.py
from django.urls import path
from .views import BookListView, BookDetailView

app_name = 'books'

urlpatterns = [
    path('list/', BookListView.as_view(), name= 'list'),
    path('list/<pk>', BookDetailView.as_view(), name='detail')
]

bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sales.urls')),
    path('books/', include ('books.urls')),
    path('login/', login_view, name = 'login'),
    path('logout/', logout_view, name = 'logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sales/urls.py
from django.urls import path
from .views import home, records

app_name= 'sales'

urlpatterns= [
    path('', home, name = 'home'),
    path('sales/', records, name = 'records'),
]

books/models.py
from django.db import models
from django.shortcuts import reverse

# Create your models here.

genre_choices= (
        ('classic','Classic'),
        ('romantic', 'Romantic'),
        ('comic', 'Comic'),
        ('fantasy', 'Fantasy'),
        ('horror', 'Horror'),
        ('educational', 'Educational')
    )

book_type_choices=(
        ('hardcover', 'Hardcover'),
        ('ebook', 'E-Book'),
        ('audiobook', 'Audiobook')
    )

class Book(models.Model):
    name= models.CharField(max_length=120)
    author_name= models.CharField(max_length=120)
    price= models.FloatField(help_text= 'in US dollars $')
    genre= models.CharField(max_length=12, 
                            choices=genre_choices, default='classic')
    book_type= models.CharField(max_length=12, 
                            choices= book_type_choices, default='hardcover')
    pic= models.ImageField(upload_to='books', default='no_picture.jpg')
    
    
    def __str__(self):
        return str(self.name)
    
    def get_absolute_url(self):
        return reverse ('books:detail', kwargs={'pk': self.pk})
    

customers/models.py
from django.db import models

# Create your models here.

# Customer clsss is table in the database
class Customer(models.Model):
    #the attributes (name and notes)are columns in the table
    #name and notes attributes are CharField and TextField (rows)
    name= models.CharField(max_length=120)
    notes= models.TextField()
    pic= models.ImageField(upload_to='customers', default='no_picture.jpg')

    def __str__(self):
        return str(self.name)
    

sales/models.py
from django.db import models
from books.models import Book

# Create your models here.

class Sale(models.Model):
    book= models.ForeignKey(Book, on_delete=models.CASCADE)
    quantity= models.PositiveIntegerField()
    price= models.FloatField()
    date_created= models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"id: {self.id}, book: {self.book.name}, quantity: {self.quantity}, price: {self.price}"
    


    

salespersons/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Salesperson(models.Model):
    username= models.OneToOneField(User, on_delete=models.CASCADE)
    name= models.CharField(max_length=120)
    bio= models.TextField(default="no bio...")
    pic= models.ImageField(upload_to='salespersons', default='no_picture.jpg')

    def __str__(self):
        return f"Profile of {self.user.username}"

sales/forms.py
from django import forms

# specify choices as a tuple
CHART__CHOICES = (          #specify choices as a tuple
   ('#1', 'Bar chart'),    # when user selects "Bar chart", it is stored as "#1"
   ('#2', 'Pie chart'),
   ('#3', 'Line chart')
   )

# define class-based Form imported from Django forms

class SalesSearchForm(forms.Form): 
   book_title= forms.CharField(max_length=120)
   chart_type = forms.ChoiceField(choices=CHART__CHOICES)

books/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView 
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Book

# Create your views here.

# class-based view with added class-based 'protected' 
# view LoginRequiredMixin
class BookListView(LoginRequiredMixin,ListView):
    
    model = Book     # specity the template
    template_name = 'books/main.html'   #specify the template

class BookDetailView(LoginRequiredMixin, DetailView):
    
    model = Book   # specify the model
    template_name = 'books/detail.html'  #specify the template

bookstore/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm

# define a function view called login_view that takes a request
# from a user.
def login_view(request):
    error_message = None
    form = AuthenticationForm()

    # when user hits 'login' button, then POST reqeust is generated
    if request.method =='POST':

        # read the data sent by the form via POST request
        form = AuthenticationForm(data=request.POST)

        # check if form is valid
        if form.is_valid():
        
            username = form.cleaned_data.get('username') # read username
        
            password = form.cleaned_data.get('password') # read password

            # use Django authenticate function to validate the user
            user = authenticate(username=username, password=password)
        
            # if user is authenticated then use pre-definded Django function
            # to log in.
            if user is not None:
                login(request, user)
                return redirect('sales:records') # sends the user to desired page
            
        else:
            error_message = 'oops...something went wrong'
    
    # prepare data to send from view to template
    context ={
        'form': form,
        'error_message': error_message
    } 
    # load the login page using 'contect' information 
    return render(request, 'auth/login.html', context)  


# define a function view called logout_view that takes a request from user

def logout_view(request):
    logout(request) # the use pre-defined Django function to logout
    return redirect('login')  # after logging out go to login form    

customers/views.py
from django.shortcuts import render

# Create your views here.

sales/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from .forms import SalesSearchForm
from .models import Sale
import pandas as pd
from .utils import get_bookname_from_id, get_chart

# Create your views here.

def home(request):
    return render(request, 'sales/home.html')

# define function-based view - records(request)
@login_required
def records(request):
	#create an instance of SalesSearchForm that you defined in sales/forms.py
	form = SalesSearchForm(request.POST or None)
	sales_df=None	#initialize dataframe to None
	chart = None	#initialize chart to None

	#check if the button is clicked
	if request.method =='POST':
		#read book_title and chart_type
		book_title = request.POST.get('book_title')
		chart_type = request.POST.get('chart_type')

		#apply filter to extract data
		qs =Sale.objects.filter(book__name=book_title)
		if len(qs) >0:		#if data found
			#convert the queryset values to pandas dataframe
			sales_df=pd.DataFrame(qs.values())	
			#convert the ID to Name of book
			sales_df['book_id']=sales_df['book_id'].apply(get_bookname_from_id)
			#call get_chart by passing chart_type from user input, sales dataframe and labels
			chart=get_chart(chart_type, sales_df, labels=sales_df['date_created'].values)
			#convert the dataframe to HTML
			sales_df=sales_df.to_html()

        #display in terminal - debgging during development
        # print(book_title, chart_type)

        # print ('Exploring querysets:')
        # print ('Case 1: Output of Sale.objects.all()')
        # qs=Sale.objects.all()
        # print (qs)

        # print ('Case 2: Output of Sale.objects.filter(book__name=book_title)')
        # qs =Sale.objects.filter(book__name=book_title)
        # print (qs)

        # print ('Case 3: Output of qs.values()')
        # print (qs.values())

        # print ('Case 4: Output of qs.values_list()')
        # print (qs.values_list())

        # print ('Case 5: Output of Sale.objects.get(id=1)')
        # obj = Sale.objects.get(id=1)
        # print (obj)

    #pack up data to be sent to template in the context dictionary
	context={
			'form': form,
			'sales_df': sales_df,
			'chart': chart
			}

	#load the sales/record.html page using the data that you just prepared
	return render(request, 'sales/records.html', context)

salespersons/views.py
from django.shortcuts import render

# Create your views here.

books/templates/books/detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>Book Detail</title>
</head>
<body>
    <div><img src="{% static 'sales/images/books-unsplash.jpg' %}" alt="home" class="background-image"></div>
    <ul>
        <li><a href ="{%url 'books:list' %}"> Books </a></li>
        <li><a href="{% url 'sales:records' %}">Records</a></li>
        <li><a href="{%url 'logout' %}">Logout</a></li>
    </ul>

<div class="page-wrapper">
<div class="main-content">
    <div class="book-card">
        <img src="{{object.pic.url}}" width="200" height="300" alt="">
        <div class="book-detail-container">
            <h2> {{object.name}}</h2>
            <p><b>Title: </b> {{object.name}}</p>
            <p><b>Author: </b> {{object.author_name}}</p>
            <p><b>Genre: </b> {{object.genre}}</p>
            <p><b>Book Type: </b> {{object.book_type}}</p>
            <p><b>Price: </b> {{object.price}} </p>
        </div>    
    </div>
</div>
    <footer>
        Photo by <a
            href="https://unsplash.com/@gulfergin_01?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">
            Gülfer ERGİN</a> on
        <a
            href="https://unsplash.com/photos/white-and-brown-book-on-brown-woven-surface-LUGuCtvlk1Q?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
    </footer>
    </div>
</body>
</html>

books/templates/books/main.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>Books</title>
</head>

<body>
    <div><img src="{% static 'sales/images/books-unsplash.jpg' %}" alt="home" class="background-image"></div>
    <ul>
        <li><a href ="{%url 'books:list' %}"> Books </a></li>
        <li><a href="{% url 'sales:records' %}">Records</a></li>
        <li><a href="{%url 'logout' %}">Logout</a></li>
    </ul>
    <div>
        <h1>Books</h1> {% comment%} HTML tag for heading {% endcomment%}
    </div>

    <div>
        <table>
            <tr>
                <td>Book Titles</td>
                <td>Book Images</td>
            </tr>

            {% for object in object_list %}

            <tr>
                <td><a href="{{object.get_absolute_url}}"> {% comment%} add links to book names {% endcomment%}
                        {{object.name}}
                    </a></td>
                <td><img src="{{object.pic.url}}" width="150" height="200" /></td>
            </tr>
            {% endfor %}
        </table>
    </div>

    <footer>
        Photo by <a
            href="https://unsplash.com/@gulfergin_01?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">
            Gülfer ERGİN</a> on
        <a
            href="https://unsplash.com/photos/white-and-brown-book-on-brown-woven-surface-LUGuCtvlk1Q?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
    </footer>
</body>

</html>

sales/templates/sales/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>Bookstore Home</title>
    <script src="{% static 'sales/home.js' %}" defer></script>

</head>
<body>
    <div><img src="{% static 'sales/images/books-unsplash.jpg' %}" alt="home" class="background-image"></div>
    
    <div class="main-content">
        <h1>Welcome to our Bookstore</h1>
        <a href="{%url 'login' %}">Login</a>

    </div>
    <footer>
        Photo by <a
            href="https://unsplash.com/@gulfergin_01?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">
            Gülfer ERGİN</a> on
        <a
            href="https://unsplash.com/photos/white-and-brown-book-on-brown-woven-surface-LUGuCtvlk1Q?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
    </footer>
</body>
</html>

sales/templates/sales/records.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=h1, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>Records</title>
</head>

<body>
    <div><img src="{% static 'sales/images/books-unsplash.jpg' %}" alt="home" class="background-image"></div>
    <ul>
        <li><a href ="{%url 'books:list' %}">Books </a></li>
        <li><a href="{% url 'sales:records' %}">Records</a></li>
        <li><a href="{%url 'logout' %}">Logout</a></li>   
    </ul>
    
    <div class="records-content">
        <h1>Search for sales records</h1>

        <form action="" method="POST">
            {% csrf_token %}
            {{form}}
            <button type="submit">search</button>
        </form>
    </div>
    <div class="main-content">
        <div class="chart-data">
            {% if sales_df %}
            {{sales_df|safe}}
            <br>
            <br>
            <img src="data:image/png;base64, {{chart|safe}}" alt="">
            {% else %}
           
            <h3>no data</h3>
            {% endif %}
        </div>
    </div>
    <footer>
        Photo by <a
            href="https://unsplash.com/@gulfergin_01?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">
            Gülfer ERGİN</a> on
        <a
            href="https://unsplash.com/photos/white-and-brown-book-on-brown-woven-surface-LUGuCtvlk1Q?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText">Unsplash</a>
    </footer>
</body>
</html>